# Generated by Django 5.2 on 2025-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_genre_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(related_name='genre_products', to='main.category', verbose_name='Жанр'),
        ),
    ]
