# Generated by Django 5.2 on 2025-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_genre_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(related_name='genre_products', to='main.genre', verbose_name='Жанр'),
        ),
    ]
