# Generated by Django 5.2 on 2025-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default=3, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
